// 115 lixianssp request cipher. The offline-download endpoint
// (POST https://lixian.115.com/lixianssp/) takes an RSA-encrypted body. This is
// a faithful port of p115cipher's `rsa_encrypt` (the request direction only —
// the response's success state is a plaintext top-level field, so we never need
// the asymmetric decrypt). Deterministic for the default rand key, so it is
// verified offline against vectors generated by the Python reference.

const RSA_N = BigInt(
  "0x8686980c0f5a24c4b9d43020cd2c22703ff3f450756529058b1cf88f09b8602136477198a6e2683149659bd122c33592fdb5ad47944ad1ea4d36c6b172aad6338c3bb6ac6227502d010993ac967d1aef00f0c8e038de2e4d3bc2ec368af2e9f10a6f1eda4f7262f136420c07c331b871bf139f74f3010e3c4fe57df3afb71683",
);
const RSA_E = 0x10001n;
const RSA_KEY = Uint8Array.from([0x8d, 0xa5, 0xa5, 0x8d]);
const G_KEY_L = Uint8Array.from([0x78, 0x06, 0xad, 0x4c, 0x33, 0x86, 0x5d, 0x18, 0x4c, 0x01, 0x3f, 0x46]);

/**
 * 115's xor: the first `len % 4` bytes xor key[:that], then `len(key)`-sized
 * chunks each xor key from the start. (The leading-partial size is mod 4
 * regardless of key length — a 115 quirk, reproduced exactly.)
 */
function xor115(src: Uint8Array, key: Uint8Array): Uint8Array {
  const out = new Uint8Array(src.length);
  const head = src.length % 4;
  for (let k = 0; k < head; k += 1) {
    out[k] = src[k]! ^ key[k]!;
  }
  for (let a = head; a < src.length; a += key.length) {
    const size = Math.min(key.length, src.length - a);
    for (let k = 0; k < size; k += 1) {
      out[a + k] = src[a + k]! ^ key[k]!;
    }
  }
  return out;
}

function bytesToBigInt(bytes: Uint8Array): bigint {
  let result = 0n;
  for (const byte of bytes) {
    result = (result << 8n) | BigInt(byte);
  }
  return result;
}

function bigIntToBytes(value: bigint, length: number): Uint8Array {
  const bytes = new Uint8Array(length);
  let remaining = value;
  for (let i = length - 1; i >= 0; i -= 1) {
    bytes[i] = Number(remaining & 0xffn);
    remaining >>= 8n;
  }
  return bytes;
}

function modPow(base: bigint, exponent: bigint, modulus: bigint): bigint {
  let result = 1n;
  let b = base % modulus;
  let e = exponent;
  while (e > 0n) {
    if (e & 1n) {
      result = (result * b) % modulus;
    }
    e >>= 1n;
    b = (b * b) % modulus;
  }
  return result;
}

/** 128-byte block: 0x00, (126 - len) bytes of 0x02, 0x00, then the message. */
function padPkcs1(message: Uint8Array): bigint {
  const block = new Uint8Array(128);
  const fill = 126 - message.length;
  for (let k = 0; k < fill; k += 1) {
    block[1 + k] = 0x02;
  }
  block.set(message, 2 + fill);
  return bytesToBigInt(block);
}

function rsaEncryptWithPubkey(data: Uint8Array): Uint8Array {
  const out: number[] = [];
  for (let l = 0; l < data.length; l += 117) {
    const chunk = data.subarray(l, l + 117);
    const cipher = modPow(padPkcs1(chunk), RSA_E, RSA_N);
    out.push(...bigIntToBytes(cipher, 128));
  }
  return Uint8Array.from(out);
}

/** Encrypt a request body for the 115 lixianssp endpoint; returns base64. */
export function lixianRsaEncrypt(data: Uint8Array): string {
  const reversed = xor115(data, RSA_KEY).reverse();
  const xorData = new Uint8Array(16 + reversed.length);
  xorData.set(xor115(reversed, G_KEY_L), 16);
  return Buffer.from(rsaEncryptWithPubkey(xorData)).toString("base64");
}
