import { describe, expect, it } from "vitest";
import { lixianRsaEncrypt } from "../src/pan115-lixian-cipher.js";

// Vectors generated by the Python reference (p115cipher.rsa_encrypt), which is
// deterministic for the default rand key. A faithful port must reproduce them
// byte-for-byte.
describe("lixianRsaEncrypt (115 offline-task request cipher)", () => {
  it("matches the reference for a magnet add-task payload", () => {
    const payload =
      '{"url":"magnet:?xt=urn:btih:ABCDEF","wp_path_id":"12345","ac":"add_task_url","app_ver":"99.99.99.99"}';
    expect(lixianRsaEncrypt(new TextEncoder().encode(payload))).toBe(
      "eoKA4c8H2mDKwMbsVPOxJmMKHGCE7SxVVy2Wr5S+9wdse9Z4QkgpDiYYXQb4tS9cfP+HS+3DVzb6arHsQhxR7ARB89sXslySsGX4YSTCq1M+jtK+pIaKDr4J2rQkCdWSvapGRg2Xg+UbdOHr29lWkBHRYSQoc7mRJxglOd60Jdk=",
    );
  });

  it("matches the reference for a short input", () => {
    expect(lixianRsaEncrypt(new TextEncoder().encode("hello"))).toBe(
      "Wo2FTEiVl+yLT5jEa7WFXGGv3MB3xw6JyYb1bNdV6cJ+5NOORITtM2c6selLnjMH8mnV7DHqVy1G0Fap5h9P4yTXbN/UTVxgC2UlNLVDMFppR5IlsO5YhGxjySir1KYfEywul2eT7Wb9vv46KNUoniKP87v7ezAnU+FAJhbxu8w=",
    );
  });

  it("matches the reference for empty input", () => {
    expect(lixianRsaEncrypt(new Uint8Array(0))).toBe(
      "gss8BiTOuTPZ6/P8OXHFi87fPxOuUVzEr8cek9pV7LavJ3JiXqIcPr6JNVtIMg8wOP89zPrG5/q8cHRufHEnfzVoMYPEAQrHob6eQ5zUOQcV8hurvDYP96LTEimD8tMwAVd2SeCOUShASNSSOz4pb3DpZwJUzuCs7P/zjvlQOiM=",
    );
  });
});
